source 'http://rubygems.org'

gem 'rails'
gem 'thin'
gem 'unicorn'
gem 'bundler'
gem 'mongo'
gem 'bson'
gem 'bson_ext'
gem 'mongoid'
gem 'jquery-rails'
gem 'json'
gem 'haml'
gem 'capistrano'
gem 'rvm-capistrano'
gem 'capistrano-unicorn'
gem 'less-rails-bootstrap'
gem 'therubyracer', '0.10.2'
gem 'uglifier'
