development:
  sessions:
    default:
      database: minetwork
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: minetwork
      hosts:
        - localhost:27017

staging:
  sessions:
    default:
      database: minetwork
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: minetwork
      hosts:
        - localhost:27017
