development:
  sessions:
    default:
      database: minetwork
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: minetwork
      hosts:
        - localhost:27017

staging:
  options:
    identity_map_enabled: true
  sessions:
    default:
      hosts:
        - localhost:27017
      database: minetwork

production:
  options:
    identity_map_enabled: true
  sessions:
    default:
      hosts:
        - localhost:27017
      database: minetwork
